# Generated by Django 3.2.8 on 2021-10-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kcal_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='kcal',
        ),
    ]
