# Generated by Django 3.2.8 on 2021-10-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(),
        ),
    ]
