# Generated by Django 3.2.8 on 2021-10-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='kcal_app.MealIngredientWeight', to='kcal_app.Ingredient'),
        ),
    ]
