# Generated by Django 3.2.8 on 2021-10-17 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kcal_app', '0003_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='kcal_app.profile'),
        ),
    ]
