# Generated by Django 3.2.8 on 2021-10-18 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kcal_app', '0005_alter_plan_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='day',
            unique_together=set(),
        ),
    ]
