# Generated by Django 3.2.8 on 2021-10-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcal_app', '0008_alter_day_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='carbs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='proteins',
            field=models.FloatField(),
        ),
    ]
