# Generated by Django 3.2.8 on 2021-10-18 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kcal_app', '0009_auto_20211018_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='name',
        ),
        migrations.CreateModel(
            name='ActivityDayTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in_minutes', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kcal_app.activity')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kcal_app.day')),
            ],
        ),
    ]
