# Generated by Django 3.2.8 on 2021-10-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcal_app', '0012_alter_profile_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='base_kcal',
            field=models.IntegerField(default=2000),
        ),
    ]
