# Generated by Django 3.2.8 on 2021-10-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcal_app', '0014_profile_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='day_weight',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
